# Add this options block to fix the error
options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'

steps:
  # Step 1: Install dependencies and run unit tests
  # This step uses a standard Node.js image to execute npm commands.
  # It will run 'npm install' first, then 'npm test'. If tests fail, the build stops here.
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']

  # Step 2: Build the container image (only runs if tests pass)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/mega-care-dev/mega-care-connect-repo/mega-care-connect-app:$COMMIT_SHA'
      - '.'

  # Step 3: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/mega-care-dev/mega-care-connect-repo/mega-care-connect-app:$COMMIT_SHA'

  # Step 4: Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mega-care-connect-service'
      - '--image=asia-southeast1-docker.pkg.dev/mega-care-dev/mega-care-connect-repo/mega-care-connect-app:$COMMIT_SHA'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=80'

# Store the built image in the new Artifact Registry
images:
  - 'asia-southeast1-docker.pkg.dev/mega-care-dev/mega-care-connect-repo/mega-care-connect-app:$COMMIT_SHA'
