# Add this options block to fix the error
options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'

steps:
  # Step 1: Install dependencies using Node.js v18
  # We specify a modern Node.js image to ensure compatibility with Jest.
  # We also specify 'npm' as the entrypoint for the command.
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Run unit tests using Node.js v18
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['test']

  # Step 3: Build the container image (only runs if tests pass)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/mega-care-dev/mega-care-connect-repo/mega-care-connect-app:$COMMIT_SHA'
      - '.'

  # Step 4: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/mega-care-dev/mega-care-connect-repo/mega-care-connect-app:$COMMIT_SHA'

  # Step 5: Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mega-care-connect-service'
      - '--image=asia-southeast1-docker.pkg.dev/mega-care-dev/mega-care-connect-repo/mega-care-connect-app:$COMMIT_SHA'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=80'

# Store the built image in the new Artifact Registry
images:
  - 'asia-southeast1-docker.pkg.dev/mega-care-dev/mega-care-connect-repo/mega-care-connect-app:$COMMIT_SHA'
